development:
  adapter: postgresql
  encoding: unicode
  database: gloomy_weather
  pool: 2
  username: vince
  password: vince_gloomy_weather
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>